---
- name: Deploy LAMP Stack
  hosts: Slave
  become: yes
  tasks:
    - name: Copy Bash Script
      copy:
        src: files/lamp_setup.sh
        dest: /tmp/lamp_setup.sh
        mode: 0755

    - name: Execute Bash Script
      shell: /tmp/lamp_setup.sh
      args:
        creates: /var/www/laravel/.deployed  # Ensure idempotence

    - name: Create Uptime Log Directory
      file:
        path: /var/log/uptime.log
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Set Up Cron Job for Uptime
      cron:
        name: Check Server Uptime
        minute: 0
        hour: 0
        job: "uptime >> /var/log/uptime.log"
